### ISSUE TITLE
💷 SPIKE: Investigate using AWS Lambda functions. 

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/cloud-operations-slack-bot#83]
### User Story

As a… Cloud Ops Engineer
I want to deliver the Bot with a priority on cost
So that… the bot doesn't cost too much 

### Value / Purpose

Current costs for running the bot are listed here: https://reports.cloud-platform.service.justice.gov.uk/namespace/cloudopsbot-prod

### Additional Information

Could we use DynamoDB for slack users?

### Definition of Done

Investigate using other means of delivering the cloudopsbot, specifically look at Lambda functions.

Consider shutting the bot down if not cost efficient.

**Comment by bagg3rs** [comment]
Added the use of DynamoDB
Also to clarify the costs on the namespace report they are all shared costs and by going into the namespace e.g. CloudOps bot you can see the costs and shared costs is not included.
```Costs
Amazon Relational Database Service	61.33
Amazon DynamoDB	0.91
```

**Comment by Gary-H9** [comment]
Spoke to an old colleague last Friday, this approach would involve creating AWS Lambda function(s) and an API endpoint. This would all have to be done in Terraform, at this moment I don't believe this offers enough value as a solution for us. We'd also have to significantly re-engineer the bots DB to somewhere in AWS.
