### ISSUE TITLE
:rocket:  Cloud Ops Bot to raise incidents using the SNOW API

### ISSUE THREAD

**Issue by ASTRobinson** [ministryofjustice/cloud-operations-slack-bot#85]
**User Story**
As a Cloud Ops engineer
I want to use the Cloud Ops Bot to create incidents on SNOW (Service Now).
So that I can easily manage incidents and give visibility to SNOW users.

**Value / Purpose**
Using the new SNOW API we can use the Cloud Ops Bot to raise incidents in SNOW giving stakeholders greater visibility, other Slack teams across the MoJ may also which to adopt this process if proven successful. 

**Useful Contacts**
Touhid
Gary

**Additional Information**

**Definition of Done**
Cloud Ops Bot can send requests to the SNOW API to create incident tickets.

[ ] README has been updated
[ ] User docs have been updated
[ ] Another team member has reviewed
[ ] Tests are green

**Comment by Gary-H9** [comment]
This functionality is now complete. The latest push to the PR takes the entirety of the string following "@CloudOpsBot incident <string>" and uses this as the short_description field in the ticket raised in Service Now. INC1651704 is an example of this. To complete this ticket we will review the work on Monday and then deploy via CloudPlatform.
