### ISSUE TITLE
🚀🤖  Configure the Cloud Ops Bot to send API request to MoJ SNOW

### ISSUE THREAD

**Issue by ASTRobinson** [ministryofjustice/cloud-operations-slack-bot#93]
### User Story

As a Cloud Ops engineer
I want to use the Cloud Ops Bot to send API requests to the MoJ SNOW service.
So that I can test the new API created in SNOW

### Value / Purpose
By completing this initial functionality testing, we can further develop the Cloud Ops Bot to raise incidents from Slack.

### Useful Contacts
Cloud Ops Team

### Additional Information
Does anyone have a link to the SNOW API documentation? @wanieldilson ? 

### Definition of Done
Cloud Ops Bot sends API requests to SNOW API to confirm connectivity and basic functionality. 

Example - [ ] Documentation has been written / updated
- [ ] README has been updated
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by Gary-H9** [comment]
New [PR](https://github.com/ministryofjustice/cloud-operations-slack-bot/pull/94) which makes the SNOW URL a parameter.

**Comment by Gary-H9** [comment]
https://github.com/ministryofjustice/cloud-operations-slack-bot/issues/95 Raised to capture changing the SNOW URL secret in future.
